feat: Update ci to include sonar.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -15,6 +15,7 @@ permissions:
 jobs:
   tests:
     runs-on: ubuntu-latest
+    name: Jest tests
     steps:
       - uses: actions/checkout@v3
         with:
@@ -57,9 +58,64 @@ jobs:
             echo "No changes to commit"
           fi
 
+  sonarqube:
+    runs-on: ubuntu-latest
+    name: Sonar quality gate
+    needs: tests
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          ref: ${{ github.event.pull_request.head.ref }}
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: '22.4.0'
+      - name: Install dependencies
+        run: npm install && npm install -g badge-maker &&
+      - name: Run SonarQube scan
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+        run: |
+          npx sonar-scanner \
+          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
+          -Dsonar.token=${{ secrets.SONAR_TOKEN }}
+      - name: Check Quality Gate
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+          PROJECT_KEY: "Portfolio"
+        run: |
+          res_status=$(curl -s "${SONAR_HOST_URL}/api/qualitygates/project_status?projectKey=${PROJECT_KEY}" \
+          -H "Accept: application/json" \
+          -H "Authorization: Bearer ${SONAR_TOKEN}" | grep -o '"status":"[^"]*' | head -1 | cut -d':' -f2 | tr -d '"')
+      - name: Generate Badge
+        run: |
+          if [ "$status" != "OK" ]; then
+            echo "Quality Gate failed!"
+            npx badge-maker "quality gate" "failed" "red" > sonar-badge.svg
+            exit 1
+          else
+            echo "Quality Gate passed!"
+            npx badge-maker "quality gate" "passed" "green" > sonar-badge.svg
+          fi
+      - name: Commit badge
+        if: always()
+        run: |
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+          git config --global user.name "github-actions[bot]"
+          git add sonar-badge.svg
+          if ! git diff --cached --exit-code; then
+            git commit -m "Add sonar badge"
+            git push
+          else
+            echo "No changes to commit"
+          fi
+
   deploy:
     runs-on: ubuntu-latest
-    needs: tests
+    name: Deploy to Firebase Hosting
+    needs: [tests, sonarqube]
     steps:
       - uses: actions/checkout@v3
       - name: Set up Node.js
